[2025-02-10 07:15:50,205][flwr][INFO] - Starting Flower ServerApp, config: num_rounds=20, no round_timeout
[2025-02-10 07:15:50,206][flwr][INFO] - 
[2025-02-10 07:15:50,207][flwr][INFO] - [INIT]
[2025-02-10 07:15:50,207][flwr][INFO] - Using initial global parameters provided by strategy
[2025-02-10 07:15:50,207][flwr][INFO] - Starting evaluation of initial global parameters
[2025-02-10 07:15:58,128][flwr][INFO] - initial parameters (loss, other metrics): 0.0721090440750122, {'accuracy': 0.0788}
[2025-02-10 07:15:58,128][flwr][INFO] - 
[2025-02-10 07:15:58,129][flwr][INFO] - [ROUND 1]
[2025-02-10 07:15:58,129][flwr][INFO] - configure_fit: strategy sampled 50 clients (out of 50)
[2025-02-10 07:17:04,929][flwr][INFO] - aggregate_fit: received 50 results and 0 failures
[2025-02-10 07:17:10,267][flwr][INFO] - fit progress: (1, 0.07170246067047119, {'accuracy': 0.1142}, 72.13851361200796)
[2025-02-10 07:17:10,267][flwr][INFO] - configure_evaluate: strategy sampled 50 clients (out of 50)
[2025-02-10 07:18:10,558][flwr][INFO] - aggregate_evaluate: received 50 results and 0 failures
[2025-02-10 07:18:10,558][flwr][INFO] - 
[2025-02-10 07:18:10,558][flwr][INFO] - [ROUND 2]
[2025-02-10 07:18:10,559][flwr][INFO] - configure_fit: strategy sampled 50 clients (out of 50)
[2025-02-10 07:19:11,529][flwr][INFO] - aggregate_fit: received 50 results and 0 failures
[2025-02-10 07:19:14,302][datasets.load][WARNING] - Using the latest cached version of the dataset since mnist couldn't be found on the Hugging Face Hub
[2025-02-10 07:19:14,302][datasets.packaged_modules.cache.cache][WARNING] - Found the latest cached dataset configuration 'mnist' at /home/theo_ubuntu/.cache/huggingface/datasets/mnist/mnist/0.0.0/77f3279092a1c1579b2250db8eafed0ad422088c (last modified on Sat Feb  8 20:08:50 2025).
[2025-02-10 07:19:15,955][flwr][INFO] - fit progress: (2, 0.0712978547334671, {'accuracy': 0.2261}, 197.826011105004)
[2025-02-10 07:19:15,955][flwr][INFO] - configure_evaluate: strategy sampled 50 clients (out of 50)
[2025-02-10 07:20:41,647][flwr][INFO] - aggregate_evaluate: received 50 results and 0 failures
[2025-02-10 07:20:41,647][flwr][INFO] - 
[2025-02-10 07:20:41,647][flwr][INFO] - [ROUND 3]
[2025-02-10 07:20:41,647][flwr][INFO] - configure_fit: strategy sampled 50 clients (out of 50)
[2025-02-10 07:21:45,001][flwr][INFO] - aggregate_fit: received 50 results and 0 failures
[2025-02-10 07:21:50,349][flwr][INFO] - fit progress: (3, 0.07064417238235474, {'accuracy': 0.3702}, 352.2200756610109)
[2025-02-10 07:21:50,349][flwr][INFO] - configure_evaluate: strategy sampled 50 clients (out of 50)
[2025-02-10 07:22:47,275][flwr][INFO] - aggregate_evaluate: received 50 results and 0 failures
[2025-02-10 07:22:47,275][flwr][INFO] - 
[2025-02-10 07:22:47,275][flwr][INFO] - [ROUND 4]
[2025-02-10 07:22:47,275][flwr][INFO] - configure_fit: strategy sampled 50 clients (out of 50)
[2025-02-10 07:23:47,547][flwr][INFO] - aggregate_fit: received 50 results and 0 failures
[2025-02-10 07:23:52,847][flwr][INFO] - fit progress: (4, 0.0694974667787552, {'accuracy': 0.3727}, 474.718550081001)
[2025-02-10 07:23:52,847][flwr][INFO] - configure_evaluate: strategy sampled 50 clients (out of 50)
[2025-02-10 07:24:47,928][flwr][INFO] - aggregate_evaluate: received 50 results and 0 failures
[2025-02-10 07:24:47,929][flwr][INFO] - 
[2025-02-10 07:24:47,929][flwr][INFO] - [ROUND 5]
[2025-02-10 07:24:47,929][flwr][INFO] - configure_fit: strategy sampled 50 clients (out of 50)
[2025-02-10 07:25:49,380][flwr][INFO] - aggregate_fit: received 50 results and 0 failures
[2025-02-10 07:25:55,051][flwr][INFO] - fit progress: (5, 0.06761648824214936, {'accuracy': 0.4221}, 596.9220547940058)
[2025-02-10 07:25:55,051][flwr][INFO] - configure_evaluate: strategy sampled 50 clients (out of 50)
[2025-02-10 07:26:50,772][flwr][INFO] - aggregate_evaluate: received 50 results and 0 failures
[2025-02-10 07:26:50,772][flwr][INFO] - 
[2025-02-10 07:26:50,772][flwr][INFO] - [ROUND 6]
[2025-02-10 07:26:50,772][flwr][INFO] - configure_fit: strategy sampled 50 clients (out of 50)
[2025-02-10 07:27:51,782][flwr][INFO] - aggregate_fit: received 50 results and 0 failures
[2025-02-10 07:27:57,054][flwr][INFO] - fit progress: (6, 0.0646533866405487, {'accuracy': 0.4945}, 718.9251427310082)
[2025-02-10 07:27:57,054][flwr][INFO] - configure_evaluate: strategy sampled 50 clients (out of 50)
[2025-02-10 07:28:51,408][flwr][INFO] - aggregate_evaluate: received 50 results and 0 failures
[2025-02-10 07:28:51,408][flwr][INFO] - 
[2025-02-10 07:28:51,408][flwr][INFO] - [ROUND 7]
[2025-02-10 07:28:51,408][flwr][INFO] - configure_fit: strategy sampled 50 clients (out of 50)
[2025-02-10 07:29:53,650][flwr][INFO] - aggregate_fit: received 50 results and 0 failures
[2025-02-10 07:29:59,034][flwr][INFO] - fit progress: (7, 0.06041918071508408, {'accuracy': 0.5663}, 840.9056551360118)
[2025-02-10 07:29:59,034][flwr][INFO] - configure_evaluate: strategy sampled 50 clients (out of 50)
[2025-02-10 07:30:54,749][flwr][INFO] - aggregate_evaluate: received 50 results and 0 failures
[2025-02-10 07:30:54,749][flwr][INFO] - 
[2025-02-10 07:30:54,750][flwr][INFO] - [ROUND 8]
[2025-02-10 07:30:54,750][flwr][INFO] - configure_fit: strategy sampled 50 clients (out of 50)
[2025-02-10 07:31:55,278][flwr][INFO] - aggregate_fit: received 50 results and 0 failures
[2025-02-10 07:32:00,203][flwr][INFO] - fit progress: (8, 0.055083228409290315, {'accuracy': 0.6055}, 962.0742556210025)
[2025-02-10 07:32:00,203][flwr][INFO] - configure_evaluate: strategy sampled 50 clients (out of 50)
[2025-02-10 07:32:54,276][flwr][INFO] - aggregate_evaluate: received 50 results and 0 failures
[2025-02-10 07:32:54,277][flwr][INFO] - 
[2025-02-10 07:32:54,277][flwr][INFO] - [ROUND 9]
[2025-02-10 07:32:54,277][flwr][INFO] - configure_fit: strategy sampled 50 clients (out of 50)
[2025-02-10 07:33:55,215][flwr][INFO] - aggregate_fit: received 50 results and 0 failures
[2025-02-10 07:34:00,190][flwr][INFO] - fit progress: (9, 0.0492591718673706, {'accuracy': 0.6491}, 1082.061019738001)
[2025-02-10 07:34:00,190][flwr][INFO] - configure_evaluate: strategy sampled 50 clients (out of 50)
[2025-02-10 07:34:54,907][flwr][INFO] - aggregate_evaluate: received 50 results and 0 failures
[2025-02-10 07:34:54,908][flwr][INFO] - 
[2025-02-10 07:34:54,908][flwr][INFO] - [ROUND 10]
[2025-02-10 07:34:54,908][flwr][INFO] - configure_fit: strategy sampled 50 clients (out of 50)
[2025-02-10 07:35:56,241][flwr][INFO] - aggregate_fit: received 50 results and 0 failures
[2025-02-10 07:36:02,061][flwr][INFO] - fit progress: (10, 0.04356249815225601, {'accuracy': 0.6676}, 1203.9328245979996)
[2025-02-10 07:36:02,062][flwr][INFO] - configure_evaluate: strategy sampled 50 clients (out of 50)
[2025-02-10 07:36:42,016][flwr][ERROR] - An exception was raised when processing a message by RayBackend
[2025-02-10 07:36:42,016][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=1760, ip=172.27.85.201, actor_id=b1fce2f733c8941b4a66f76401000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f9d27dca8d0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=1760, ip=172.27.85.201, actor_id=b1fce2f733c8941b4a66f76401000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f9d27dca8d0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 58, in run
    out_message = app(message=message, context=context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
             ^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/client_utils.py", line 105, in client_fn
    trainloader, valloader, _= load_datasets(cfg, partition_id)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/data_utils.py", line 27, in load_datasets
    partition = fds.load_partition(partition_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 177, in load_partition
    self._prepare_dataset()
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 314, in _prepare_dataset
    self._dataset = datasets.load_dataset(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 2132, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 1890, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
                                       ^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 342, in __init__
    self.config, self.config_id = self._create_builder_config(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 597, in _create_builder_config
    builder_config._resolve_data_files(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 206, in _resolve_data_files
    self.data_files = self.data_files.resolve(base_path, download_config)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 818, in resolve
    out[key] = data_files_patterns_list.resolve(base_path, download_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 771, in resolve
    resolve_pattern(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 388, in resolve_pattern
    for filepath, info in fs.glob(pattern, detail=True, **glob_kwargs).items()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 521, in glob
    return super().glob(path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 611, in glob
    allpaths = self.find(root, maxdepth=depth, withdirs=True, detail=True, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 556, in find
    return super().find(
           ^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 502, in find
    out[path] = self.info(path)
                ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 719, in info
    paths_info = self._api.get_paths_info(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 3303, in get_paths_info
    hf_raise_for_status(response)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 477, in hf_raise_for_status
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=1760, ip=172.27.85.201, actor_id=b1fce2f733c8941b4a66f76401000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f9d27dca8d0>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c
[2025-02-10 07:36:42,018][flwr][ERROR] - Traceback (most recent call last):
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/vce_api.py", line 112, in worker
    out_mssg, updated_context = backend.process_message(message, context)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py", line 187, in process_message
    raise ex
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py", line 175, in process_message
    ) = self.pool.fetch_result_and_return_actor_to_pool(future)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 478, in fetch_result_and_return_actor_to_pool
    _, out_mssg, updated_context = ray.get(future)
                                   ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=1760, ip=172.27.85.201, actor_id=b1fce2f733c8941b4a66f76401000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f9d27dca8d0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=1760, ip=172.27.85.201, actor_id=b1fce2f733c8941b4a66f76401000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f9d27dca8d0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 58, in run
    out_message = app(message=message, context=context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
             ^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/client_utils.py", line 105, in client_fn
    trainloader, valloader, _= load_datasets(cfg, partition_id)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/data_utils.py", line 27, in load_datasets
    partition = fds.load_partition(partition_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 177, in load_partition
    self._prepare_dataset()
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 314, in _prepare_dataset
    self._dataset = datasets.load_dataset(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 2132, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 1890, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
                                       ^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 342, in __init__
    self.config, self.config_id = self._create_builder_config(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 597, in _create_builder_config
    builder_config._resolve_data_files(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 206, in _resolve_data_files
    self.data_files = self.data_files.resolve(base_path, download_config)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 818, in resolve
    out[key] = data_files_patterns_list.resolve(base_path, download_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 771, in resolve
    resolve_pattern(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 388, in resolve_pattern
    for filepath, info in fs.glob(pattern, detail=True, **glob_kwargs).items()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 521, in glob
    return super().glob(path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 611, in glob
    allpaths = self.find(root, maxdepth=depth, withdirs=True, detail=True, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 556, in find
    return super().find(
           ^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 502, in find
    out[path] = self.info(path)
                ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 719, in info
    paths_info = self._api.get_paths_info(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 3303, in get_paths_info
    hf_raise_for_status(response)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 477, in hf_raise_for_status
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=1760, ip=172.27.85.201, actor_id=b1fce2f733c8941b4a66f76401000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f9d27dca8d0>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

[2025-02-10 07:37:04,138][flwr][ERROR] - An exception was raised when processing a message by RayBackend
[2025-02-10 07:37:04,138][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=1758, ip=172.27.85.201, actor_id=6083c3d932a3514c832c8a4f01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f3540371cd0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=1758, ip=172.27.85.201, actor_id=6083c3d932a3514c832c8a4f01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f3540371cd0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 58, in run
    out_message = app(message=message, context=context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
             ^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/client_utils.py", line 105, in client_fn
    trainloader, valloader, _= load_datasets(cfg, partition_id)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/data_utils.py", line 27, in load_datasets
    partition = fds.load_partition(partition_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 177, in load_partition
    self._prepare_dataset()
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 314, in _prepare_dataset
    self._dataset = datasets.load_dataset(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 2132, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 1890, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
                                       ^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 342, in __init__
    self.config, self.config_id = self._create_builder_config(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 597, in _create_builder_config
    builder_config._resolve_data_files(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 206, in _resolve_data_files
    self.data_files = self.data_files.resolve(base_path, download_config)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 818, in resolve
    out[key] = data_files_patterns_list.resolve(base_path, download_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 771, in resolve
    resolve_pattern(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 388, in resolve_pattern
    for filepath, info in fs.glob(pattern, detail=True, **glob_kwargs).items()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 521, in glob
    return super().glob(path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 611, in glob
    allpaths = self.find(root, maxdepth=depth, withdirs=True, detail=True, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 556, in find
    return super().find(
           ^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 502, in find
    out[path] = self.info(path)
                ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 719, in info
    paths_info = self._api.get_paths_info(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 3303, in get_paths_info
    hf_raise_for_status(response)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 477, in hf_raise_for_status
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=1758, ip=172.27.85.201, actor_id=6083c3d932a3514c832c8a4f01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f3540371cd0>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c
[2025-02-10 07:37:04,139][flwr][ERROR] - Traceback (most recent call last):
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/vce_api.py", line 112, in worker
    out_mssg, updated_context = backend.process_message(message, context)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py", line 187, in process_message
    raise ex
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py", line 175, in process_message
    ) = self.pool.fetch_result_and_return_actor_to_pool(future)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 478, in fetch_result_and_return_actor_to_pool
    _, out_mssg, updated_context = ray.get(future)
                                   ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=1758, ip=172.27.85.201, actor_id=6083c3d932a3514c832c8a4f01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f3540371cd0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=1758, ip=172.27.85.201, actor_id=6083c3d932a3514c832c8a4f01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f3540371cd0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 58, in run
    out_message = app(message=message, context=context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
             ^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/client_utils.py", line 105, in client_fn
    trainloader, valloader, _= load_datasets(cfg, partition_id)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/data_utils.py", line 27, in load_datasets
    partition = fds.load_partition(partition_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 177, in load_partition
    self._prepare_dataset()
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 314, in _prepare_dataset
    self._dataset = datasets.load_dataset(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 2132, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 1890, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
                                       ^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 342, in __init__
    self.config, self.config_id = self._create_builder_config(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 597, in _create_builder_config
    builder_config._resolve_data_files(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 206, in _resolve_data_files
    self.data_files = self.data_files.resolve(base_path, download_config)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 818, in resolve
    out[key] = data_files_patterns_list.resolve(base_path, download_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 771, in resolve
    resolve_pattern(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 388, in resolve_pattern
    for filepath, info in fs.glob(pattern, detail=True, **glob_kwargs).items()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 521, in glob
    return super().glob(path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 611, in glob
    allpaths = self.find(root, maxdepth=depth, withdirs=True, detail=True, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 556, in find
    return super().find(
           ^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 502, in find
    out[path] = self.info(path)
                ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 719, in info
    paths_info = self._api.get_paths_info(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 3303, in get_paths_info
    hf_raise_for_status(response)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 477, in hf_raise_for_status
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=1758, ip=172.27.85.201, actor_id=6083c3d932a3514c832c8a4f01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f3540371cd0>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

[2025-02-10 07:38:30,331][flwr][INFO] - aggregate_evaluate: received 48 results and 2 failures
[2025-02-10 07:38:30,331][flwr][INFO] - 
[2025-02-10 07:38:30,332][flwr][INFO] - [ROUND 11]
[2025-02-10 07:38:30,332][flwr][INFO] - configure_fit: strategy sampled 50 clients (out of 50)
[2025-02-10 07:39:31,071][flwr][INFO] - aggregate_fit: received 50 results and 0 failures
[2025-02-10 07:39:36,422][flwr][INFO] - fit progress: (11, 0.038663994431495666, {'accuracy': 0.6854}, 1418.2935838160047)
[2025-02-10 07:39:36,422][flwr][INFO] - configure_evaluate: strategy sampled 50 clients (out of 50)
[2025-02-10 07:40:31,869][flwr][INFO] - aggregate_evaluate: received 50 results and 0 failures
[2025-02-10 07:40:31,870][flwr][INFO] - 
[2025-02-10 07:40:31,870][flwr][INFO] - [ROUND 12]
[2025-02-10 07:40:31,870][flwr][INFO] - configure_fit: strategy sampled 50 clients (out of 50)
[2025-02-10 07:41:33,517][flwr][INFO] - aggregate_fit: received 50 results and 0 failures
[2025-02-10 07:41:39,198][flwr][INFO] - fit progress: (12, 0.034476811385154724, {'accuracy': 0.7088}, 1541.0698939350114)
[2025-02-10 07:41:39,199][flwr][INFO] - configure_evaluate: strategy sampled 50 clients (out of 50)
[2025-02-10 07:42:34,105][flwr][INFO] - aggregate_evaluate: received 50 results and 0 failures
[2025-02-10 07:42:34,106][flwr][INFO] - 
[2025-02-10 07:42:34,106][flwr][INFO] - [ROUND 13]
[2025-02-10 07:42:34,106][flwr][INFO] - configure_fit: strategy sampled 50 clients (out of 50)
[2025-02-10 07:43:34,596][flwr][INFO] - aggregate_fit: received 50 results and 0 failures
[2025-02-10 07:43:39,825][flwr][INFO] - fit progress: (13, 0.030940689158439637, {'accuracy': 0.7331}, 1661.6964021300082)
[2025-02-10 07:43:39,825][flwr][INFO] - configure_evaluate: strategy sampled 50 clients (out of 50)
[2025-02-10 07:44:34,027][flwr][INFO] - aggregate_evaluate: received 50 results and 0 failures
[2025-02-10 07:44:34,028][flwr][INFO] - 
[2025-02-10 07:44:34,028][flwr][INFO] - [ROUND 14]
[2025-02-10 07:44:34,028][flwr][INFO] - configure_fit: strategy sampled 50 clients (out of 50)
[2025-02-10 07:45:33,463][flwr][INFO] - aggregate_fit: received 50 results and 0 failures
[2025-02-10 07:45:38,357][flwr][INFO] - fit progress: (14, 0.028284626081585884, {'accuracy': 0.7398}, 1780.2286685849976)
[2025-02-10 07:45:38,357][flwr][INFO] - configure_evaluate: strategy sampled 50 clients (out of 50)
[2025-02-10 07:46:33,354][flwr][INFO] - aggregate_evaluate: received 50 results and 0 failures
[2025-02-10 07:46:33,354][flwr][INFO] - 
[2025-02-10 07:46:33,354][flwr][INFO] - [ROUND 15]
[2025-02-10 07:46:33,354][flwr][INFO] - configure_fit: strategy sampled 50 clients (out of 50)
[2025-02-10 07:47:33,473][flwr][INFO] - aggregate_fit: received 50 results and 0 failures
[2025-02-10 07:47:38,379][flwr][INFO] - fit progress: (15, 0.02584984960258007, {'accuracy': 0.7565}, 1900.250936772005)
[2025-02-10 07:47:38,380][flwr][INFO] - configure_evaluate: strategy sampled 50 clients (out of 50)
[2025-02-10 07:48:32,976][flwr][INFO] - aggregate_evaluate: received 50 results and 0 failures
[2025-02-10 07:48:32,976][flwr][INFO] - 
[2025-02-10 07:48:32,976][flwr][INFO] - [ROUND 16]
[2025-02-10 07:48:32,976][flwr][INFO] - configure_fit: strategy sampled 50 clients (out of 50)
[2025-02-10 07:49:34,110][flwr][INFO] - aggregate_fit: received 50 results and 0 failures
[2025-02-10 07:49:39,376][flwr][INFO] - fit progress: (16, 0.0238441935390234, {'accuracy': 0.7691}, 2021.2472732330061)
[2025-02-10 07:49:39,376][flwr][INFO] - configure_evaluate: strategy sampled 50 clients (out of 50)
[2025-02-10 07:50:34,197][flwr][INFO] - aggregate_evaluate: received 50 results and 0 failures
[2025-02-10 07:50:34,197][flwr][INFO] - 
[2025-02-10 07:50:34,197][flwr][INFO] - [ROUND 17]
[2025-02-10 07:50:34,197][flwr][INFO] - configure_fit: strategy sampled 50 clients (out of 50)
[2025-02-10 07:51:35,659][flwr][INFO] - aggregate_fit: received 50 results and 0 failures
[2025-02-10 07:51:41,207][flwr][INFO] - fit progress: (17, 0.02246026571691036, {'accuracy': 0.7732}, 2143.078838775007)
[2025-02-10 07:51:41,208][flwr][INFO] - configure_evaluate: strategy sampled 50 clients (out of 50)
[2025-02-10 07:52:35,352][flwr][INFO] - aggregate_evaluate: received 50 results and 0 failures
[2025-02-10 07:52:35,352][flwr][INFO] - 
[2025-02-10 07:52:35,352][flwr][INFO] - [ROUND 18]
[2025-02-10 07:52:35,353][flwr][INFO] - configure_fit: strategy sampled 50 clients (out of 50)
[2025-02-10 07:53:36,193][flwr][INFO] - aggregate_fit: received 50 results and 0 failures
[2025-02-10 07:53:41,708][flwr][INFO] - fit progress: (18, 0.021432646051049234, {'accuracy': 0.781}, 2263.5798884180113)
[2025-02-10 07:53:41,709][flwr][INFO] - configure_evaluate: strategy sampled 50 clients (out of 50)
[2025-02-10 07:54:36,993][flwr][INFO] - aggregate_evaluate: received 50 results and 0 failures
[2025-02-10 07:54:36,993][flwr][INFO] - 
[2025-02-10 07:54:36,993][flwr][INFO] - [ROUND 19]
[2025-02-10 07:54:36,994][flwr][INFO] - configure_fit: strategy sampled 50 clients (out of 50)
[2025-02-10 07:55:36,426][flwr][INFO] - aggregate_fit: received 50 results and 0 failures
[2025-02-10 07:55:41,635][flwr][INFO] - fit progress: (19, 0.020513462209701537, {'accuracy': 0.7874}, 2383.5061249420105)
[2025-02-10 07:55:41,635][flwr][INFO] - configure_evaluate: strategy sampled 50 clients (out of 50)
[2025-02-10 07:56:36,215][flwr][INFO] - aggregate_evaluate: received 50 results and 0 failures
[2025-02-10 07:56:36,215][flwr][INFO] - 
[2025-02-10 07:56:36,215][flwr][INFO] - [ROUND 20]
[2025-02-10 07:56:36,215][flwr][INFO] - configure_fit: strategy sampled 50 clients (out of 50)
[2025-02-10 07:57:37,266][flwr][INFO] - aggregate_fit: received 50 results and 0 failures
[2025-02-10 07:57:42,202][flwr][INFO] - fit progress: (20, 0.01976482740342617, {'accuracy': 0.7951}, 2504.0737341870117)
[2025-02-10 07:57:42,202][flwr][INFO] - configure_evaluate: strategy sampled 50 clients (out of 50)
[2025-02-10 07:58:37,862][flwr][INFO] - aggregate_evaluate: received 50 results and 0 failures
[2025-02-10 07:58:37,863][flwr][INFO] - 
[2025-02-10 07:58:37,863][flwr][INFO] - [SUMMARY]
[2025-02-10 07:58:37,863][flwr][INFO] - Run finished 20 round(s) in 2559.73s
[2025-02-10 07:58:37,864][flwr][INFO] - 	History (loss, distributed):
[2025-02-10 07:58:37,864][flwr][INFO] - 		round 1: 0.07637585608164468
[2025-02-10 07:58:37,864][flwr][INFO] - 		round 2: 0.07595222731431325
[2025-02-10 07:58:37,864][flwr][INFO] - 		round 3: 0.07526907885074616
[2025-02-10 07:58:37,864][flwr][INFO] - 		round 4: 0.0740734380086263
[2025-02-10 07:58:37,864][flwr][INFO] - 		round 5: 0.07210156047344207
[2025-02-10 07:58:37,865][flwr][INFO] - 		round 6: 0.06900406348705293
[2025-02-10 07:58:37,865][flwr][INFO] - 		round 7: 0.06457241445779799
[2025-02-10 07:58:37,865][flwr][INFO] - 		round 8: 0.058984664936860394
[2025-02-10 07:58:37,865][flwr][INFO] - 		round 9: 0.05290472749869026
[2025-02-10 07:58:37,865][flwr][INFO] - 		round 10: 0.04697325885709791
[2025-02-10 07:58:37,865][flwr][INFO] - 		round 11: 0.0419759259223938
[2025-02-10 07:58:37,865][flwr][INFO] - 		round 12: 0.037701516578594836
[2025-02-10 07:58:37,865][flwr][INFO] - 		round 13: 0.03406444213787714
[2025-02-10 07:58:37,865][flwr][INFO] - 		round 14: 0.03132401191194853
[2025-02-10 07:58:37,865][flwr][INFO] - 		round 15: 0.028743913680315022
[2025-02-10 07:58:37,865][flwr][INFO] - 		round 16: 0.02662146345774332
[2025-02-10 07:58:37,865][flwr][INFO] - 		round 17: 0.0251167547305425
[2025-02-10 07:58:37,865][flwr][INFO] - 		round 18: 0.024070681691169743
[2025-02-10 07:58:37,866][flwr][INFO] - 		round 19: 0.023062010367711383
[2025-02-10 07:58:37,866][flwr][INFO] - 		round 20: 0.022279432177543645
[2025-02-10 07:58:37,866][flwr][INFO] - 	History (loss, centralized):
[2025-02-10 07:58:37,866][flwr][INFO] - 		round 0: 0.0721090440750122
[2025-02-10 07:58:37,866][flwr][INFO] - 		round 1: 0.07170246067047119
[2025-02-10 07:58:37,866][flwr][INFO] - 		round 2: 0.0712978547334671
[2025-02-10 07:58:37,866][flwr][INFO] - 		round 3: 0.07064417238235474
[2025-02-10 07:58:37,866][flwr][INFO] - 		round 4: 0.0694974667787552
[2025-02-10 07:58:37,866][flwr][INFO] - 		round 5: 0.06761648824214936
[2025-02-10 07:58:37,866][flwr][INFO] - 		round 6: 0.0646533866405487
[2025-02-10 07:58:37,866][flwr][INFO] - 		round 7: 0.06041918071508408
[2025-02-10 07:58:37,866][flwr][INFO] - 		round 8: 0.055083228409290315
[2025-02-10 07:58:37,866][flwr][INFO] - 		round 9: 0.0492591718673706
[2025-02-10 07:58:37,867][flwr][INFO] - 		round 10: 0.04356249815225601
[2025-02-10 07:58:37,867][flwr][INFO] - 		round 11: 0.038663994431495666
[2025-02-10 07:58:37,867][flwr][INFO] - 		round 12: 0.034476811385154724
[2025-02-10 07:58:37,867][flwr][INFO] - 		round 13: 0.030940689158439637
[2025-02-10 07:58:37,867][flwr][INFO] - 		round 14: 0.028284626081585884
[2025-02-10 07:58:37,867][flwr][INFO] - 		round 15: 0.02584984960258007
[2025-02-10 07:58:37,867][flwr][INFO] - 		round 16: 0.0238441935390234
[2025-02-10 07:58:37,867][flwr][INFO] - 		round 17: 0.02246026571691036
[2025-02-10 07:58:37,867][flwr][INFO] - 		round 18: 0.021432646051049234
[2025-02-10 07:58:37,867][flwr][INFO] - 		round 19: 0.020513462209701537
[2025-02-10 07:58:37,867][flwr][INFO] - 		round 20: 0.01976482740342617
[2025-02-10 07:58:37,867][flwr][INFO] - 	History (metrics, distributed, fit):
[2025-02-10 07:58:37,867][flwr][INFO] - 	{'clients_epsilons': [(1, 0.681347138786744),
[2025-02-10 07:58:37,868][flwr][INFO] - 	                      (2, 0.681347138786744),
[2025-02-10 07:58:37,868][flwr][INFO] - 	                      (3, 0.681347138786744),
[2025-02-10 07:58:37,868][flwr][INFO] - 	                      (4, 0.681347138786744),
[2025-02-10 07:58:37,868][flwr][INFO] - 	                      (5, 0.681347138786744),
[2025-02-10 07:58:37,868][flwr][INFO] - 	                      (6, 0.681347138786744),
[2025-02-10 07:58:37,868][flwr][INFO] - 	                      (7, 0.681347138786744),
[2025-02-10 07:58:37,868][flwr][INFO] - 	                      (8, 0.681347138786744),
[2025-02-10 07:58:37,868][flwr][INFO] - 	                      (9, 0.681347138786744),
[2025-02-10 07:58:37,868][flwr][INFO] - 	                      (10, 0.681347138786744),
[2025-02-10 07:58:37,868][flwr][INFO] - 	                      (11, 0.681347138786744),
[2025-02-10 07:58:37,868][flwr][INFO] - 	                      (12, 0.681347138786744),
[2025-02-10 07:58:37,868][flwr][INFO] - 	                      (13, 0.681347138786744),
[2025-02-10 07:58:37,868][flwr][INFO] - 	                      (14, 0.681347138786744),
[2025-02-10 07:58:37,869][flwr][INFO] - 	                      (15, 0.681347138786744),
[2025-02-10 07:58:37,869][flwr][INFO] - 	                      (16, 0.681347138786744),
[2025-02-10 07:58:37,869][flwr][INFO] - 	                      (17, 0.681347138786744),
[2025-02-10 07:58:37,869][flwr][INFO] - 	                      (18, 0.681347138786744),
[2025-02-10 07:58:37,869][flwr][INFO] - 	                      (19, 0.681347138786744),
[2025-02-10 07:58:37,869][flwr][INFO] - 	                      (20, 0.681347138786744)],
[2025-02-10 07:58:37,869][flwr][INFO] - 	 'clients_losses': [(1, 2.300094848314921),
[2025-02-10 07:58:37,869][flwr][INFO] - 	                    (2, 2.288651869455973),
[2025-02-10 07:58:37,869][flwr][INFO] - 	                    (3, 2.274475246747335),
[2025-02-10 07:58:37,869][flwr][INFO] - 	                    (4, 2.2502896248499553),
[2025-02-10 07:58:37,869][flwr][INFO] - 	                    (5, 2.2093772989908853),
[2025-02-10 07:58:37,869][flwr][INFO] - 	                    (6, 2.1412518173853554),
[2025-02-10 07:58:37,870][flwr][INFO] - 	                    (7, 2.0400619152386983),
[2025-02-10 07:58:37,870][flwr][INFO] - 	                    (8, 1.8991907852490744),
[2025-02-10 07:58:37,870][flwr][INFO] - 	                    (9, 1.7304100805918377),
[2025-02-10 07:58:37,870][flwr][INFO] - 	                    (10, 1.5547064760526021),
[2025-02-10 07:58:37,870][flwr][INFO] - 	                    (11, 1.3863085010051728),
[2025-02-10 07:58:37,870][flwr][INFO] - 	                    (12, 1.2466838887532552),
[2025-02-10 07:58:37,870][flwr][INFO] - 	                    (13, 1.1298021838665009),
[2025-02-10 07:58:37,870][flwr][INFO] - 	                    (14, 1.02644362616539),
[2025-02-10 07:58:37,870][flwr][INFO] - 	                    (15, 0.9446946674982707),
[2025-02-10 07:58:37,870][flwr][INFO] - 	                    (16, 0.8756047811508179),
[2025-02-10 07:58:37,870][flwr][INFO] - 	                    (17, 0.8187417716185252),
[2025-02-10 07:58:37,870][flwr][INFO] - 	                    (18, 0.7791748931010564),
[2025-02-10 07:58:37,871][flwr][INFO] - 	                    (19, 0.7441617598930995),
[2025-02-10 07:58:37,871][flwr][INFO] - 	                    (20, 0.7169412318865458)]}
[2025-02-10 07:58:37,871][flwr][INFO] - 	History (metrics, distributed, evaluate):
[2025-02-10 07:58:37,871][flwr][INFO] - 	{'clients_accuracies': [(1, 0.11683333333333332),
[2025-02-10 07:58:37,871][flwr][INFO] - 	                        (2, 0.22466666666666668),
[2025-02-10 07:58:37,871][flwr][INFO] - 	                        (3, 0.3608333333333333),
[2025-02-10 07:58:37,871][flwr][INFO] - 	                        (4, 0.3691666666666667),
[2025-02-10 07:58:37,871][flwr][INFO] - 	                        (5, 0.41783333333333333),
[2025-02-10 07:58:37,871][flwr][INFO] - 	                        (6, 0.48133333333333334),
[2025-02-10 07:58:37,871][flwr][INFO] - 	                        (7, 0.5528333333333333),
[2025-02-10 07:58:37,871][flwr][INFO] - 	                        (8, 0.591),
[2025-02-10 07:58:37,871][flwr][INFO] - 	                        (9, 0.6331666666666667),
[2025-02-10 07:58:37,871][flwr][INFO] - 	                        (10, 0.6505208333333332),
[2025-02-10 07:58:37,871][flwr][INFO] - 	                        (11, 0.6636666666666668),
[2025-02-10 07:58:37,872][flwr][INFO] - 	                        (12, 0.6863333333333336),
[2025-02-10 07:58:37,872][flwr][INFO] - 	                        (13, 0.7151666666666668),
[2025-02-10 07:58:37,872][flwr][INFO] - 	                        (14, 0.7203333333333336),
[2025-02-10 07:58:37,872][flwr][INFO] - 	                        (15, 0.740166666666667),
[2025-02-10 07:58:37,872][flwr][INFO] - 	                        (16, 0.7556666666666666),
[2025-02-10 07:58:37,872][flwr][INFO] - 	                        (17, 0.7565),
[2025-02-10 07:58:37,872][flwr][INFO] - 	                        (18, 0.7649999999999997),
[2025-02-10 07:58:37,872][flwr][INFO] - 	                        (19, 0.7726666666666666),
[2025-02-10 07:58:37,872][flwr][INFO] - 	                        (20, 0.7811666666666666)],
[2025-02-10 07:58:37,872][flwr][INFO] - 	 'clients_losses': [(1, 0.07637585608164468),
[2025-02-10 07:58:37,872][flwr][INFO] - 	                    (2, 0.07595222731431325),
[2025-02-10 07:58:37,872][flwr][INFO] - 	                    (3, 0.07526907885074616),
[2025-02-10 07:58:37,872][flwr][INFO] - 	                    (4, 0.0740734380086263),
[2025-02-10 07:58:37,873][flwr][INFO] - 	                    (5, 0.07210156047344207),
[2025-02-10 07:58:37,873][flwr][INFO] - 	                    (6, 0.06900406348705293),
[2025-02-10 07:58:37,873][flwr][INFO] - 	                    (7, 0.06457241445779799),
[2025-02-10 07:58:37,873][flwr][INFO] - 	                    (8, 0.058984664936860394),
[2025-02-10 07:58:37,873][flwr][INFO] - 	                    (9, 0.05290472749869026),
[2025-02-10 07:58:37,873][flwr][INFO] - 	                    (10, 0.04697325885709791),
[2025-02-10 07:58:37,873][flwr][INFO] - 	                    (11, 0.0419759259223938),
[2025-02-10 07:58:37,873][flwr][INFO] - 	                    (12, 0.037701516578594836),
[2025-02-10 07:58:37,873][flwr][INFO] - 	                    (13, 0.03406444213787714),
[2025-02-10 07:58:37,873][flwr][INFO] - 	                    (14, 0.03132401191194853),
[2025-02-10 07:58:37,873][flwr][INFO] - 	                    (15, 0.028743913680315022),
[2025-02-10 07:58:37,873][flwr][INFO] - 	                    (16, 0.02662146345774332),
[2025-02-10 07:58:37,873][flwr][INFO] - 	                    (17, 0.0251167547305425),
[2025-02-10 07:58:37,874][flwr][INFO] - 	                    (18, 0.024070681691169743),
[2025-02-10 07:58:37,874][flwr][INFO] - 	                    (19, 0.023062010367711383),
[2025-02-10 07:58:37,874][flwr][INFO] - 	                    (20, 0.022279432177543645)]}
[2025-02-10 07:58:37,874][flwr][INFO] - 	History (metrics, centralized):
[2025-02-10 07:58:37,874][flwr][INFO] - 	{'accuracy': [(0, 0.0788),
[2025-02-10 07:58:37,874][flwr][INFO] - 	              (1, 0.1142),
[2025-02-10 07:58:37,874][flwr][INFO] - 	              (2, 0.2261),
[2025-02-10 07:58:37,874][flwr][INFO] - 	              (3, 0.3702),
[2025-02-10 07:58:37,874][flwr][INFO] - 	              (4, 0.3727),
[2025-02-10 07:58:37,874][flwr][INFO] - 	              (5, 0.4221),
[2025-02-10 07:58:37,874][flwr][INFO] - 	              (6, 0.4945),
[2025-02-10 07:58:37,874][flwr][INFO] - 	              (7, 0.5663),
[2025-02-10 07:58:37,874][flwr][INFO] - 	              (8, 0.6055),
[2025-02-10 07:58:37,874][flwr][INFO] - 	              (9, 0.6491),
[2025-02-10 07:58:37,875][flwr][INFO] - 	              (10, 0.6676),
[2025-02-10 07:58:37,875][flwr][INFO] - 	              (11, 0.6854),
[2025-02-10 07:58:37,875][flwr][INFO] - 	              (12, 0.7088),
[2025-02-10 07:58:37,875][flwr][INFO] - 	              (13, 0.7331),
[2025-02-10 07:58:37,875][flwr][INFO] - 	              (14, 0.7398),
[2025-02-10 07:58:37,875][flwr][INFO] - 	              (15, 0.7565),
[2025-02-10 07:58:37,875][flwr][INFO] - 	              (16, 0.7691),
[2025-02-10 07:58:37,875][flwr][INFO] - 	              (17, 0.7732),
[2025-02-10 07:58:37,875][flwr][INFO] - 	              (18, 0.781),
[2025-02-10 07:58:37,875][flwr][INFO] - 	              (19, 0.7874),
[2025-02-10 07:58:37,875][flwr][INFO] - 	              (20, 0.7951)]}
[2025-02-10 07:58:37,875][flwr][INFO] - 
